version: '3.8'

services:
  phpmailer:
    container_name: PHPMailer
    image: ghcr.io/cypac-cybersecurity/phpmailer:latest
    restart: always
    environment:
      - SMTP_HOST=smtp.example.com
      - SMTP_USER=your@email.com
      - SMTP_PASS=yourpassword
      - SMTP_SECURE=tls
      - SMTP_PORT=587
      - MAIL_FROM=your@email.com
      - MAIL_TO=recipient@email.com
    networks:
      - default
